server:
  port: 8080
  servlet:
    context-path: /erp
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/erp
    username: postgres
    password: suiyue!123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev